### ISSUE TITLE
Getting error on Dotclear 2.31.1, perhaps plugin installation is not creating required tables

### ISSUE THREAD

**Issue by AmritasyaPutra** [franck-paul/accessibleCaptcha#4]
I am getting a lot of comments so I had to turn them off altogether. I wanted to try your plugin.

My configuration:
    Installed Dotclear version is 2.31.1
    Installed PHP version is 8.3.10, next Dotclear release required 8.1 or earlier.

My site:
[ekvastra](https://finance.ekvastra.in)

Accessible captcha comes under Antispam plugin. When I try to configure it, I am getting the following error:

> Table 'dbname.dcen_captcha' doesn't exist

**Comment by franck-paul** [comment]
Will check that on a fresh install of dotclear asap!

**Comment by franck-paul** [comment]
I have no problem installing the last release of this plugin. Which version have you installed? The 2.4.2 (https://github.com/franck-paul/accessibleCaptcha/releases/tag/2.4.2) or another (and older)?

**Comment by AmritasyaPutra** [comment]
The repository still presents me "Accessible Captcha (accessibleCaptcha) | 2.1.1".

But I installed directly this one: https://github.com/franck-paul/accessibleCaptcha/releases/download/2.4.2/plugin-accessibleCaptcha-2.4.2.zip

I do see this in my Activated plugin:
Accessible Captcha (accessibleCaptcha) | 2.4.2

I did the entire exercise again but got the same message when trying to configure it:
Table 'ekvastra_dotc110.dcen_captcha' doesn't exist

**Comment by franck-paul** [comment]
May be the mySQL (or PostgreSQL/SQLite) login/password used for your installation do not allow creation of new tables/indexes… ? Could you verify this point?

**Comment by AmritasyaPutra** [comment]
The MySQL privileges are good:

Manage User Privileges
        User: dbuser_dotc110
        Database: ekvastra_dotc110
        ALL PRIVILEGES

I checked that there is nothing recent in error_log also.

**Comment by AmritasyaPutra** [comment]
I can create an admin account for you to assist with your troubleshooting. Since this is a hobby site, there’s no rush. I believe you’re also interested in exploring this for your own satisfaction, so please take as much time as you need. How would you prefer I securely share the credentials with you?

**Comment by franck-paul** [comment]
Could you try to "Uninstall" the plugin, using the according button in plugin's management, but only with the "delete version number" checked?
Then it should try to create again the missing tables.
Let me know

**Comment by AmritasyaPutra** [comment]
I am afraid I did not understand that.

I am on /admin/upgrade.php?process=Plugins#plugins page.

I see a "delete" button. This is what I used earlier to reattempt.

Here is what I see:

![plugin](https://github.com/user-attachments/assets/57bd7b19-0bd2-47b4-956e-8d591982af41)

**Comment by franck-paul** [comment]
Could you activate it and then do the uninstall (version number only) procedure?

**Comment by AmritasyaPutra** [comment]
Now I understand, you were referring to the following screen:

![plugin](https://github.com/user-attachments/assets/1af95315-d8fb-4268-b7b3-44117c92c35d)

Yes, it worked after that! Thank you.

**Comment by franck-paul** [comment]
Oh nice to read that!

So I close this issue…
